# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='메뉴 이미지')),
                ('name', models.CharField(max_length=50, verbose_name='메뉴 이름')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(max_length=200, verbose_name='업체 주소'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(verbose_name='업체 소개'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='업체 이름'),
        ),
        migrations.AddField(
            model_name='menu',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
    ]
